name: Type Coverage

on:
  push:
    paths:
      - '**.php'

jobs:
  type-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install Dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_LICENSE }}"
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute type coverage tests via Pest
        run: php artisan test --type-coverage --min=99
